/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    FuelRecorder: typeof import('./src/components/FuelRecorder.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    LogOut: typeof import('./src/components/LogOut.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserEdidt: typeof import('./src/components/UserEdidt.vue')['default']
    UserRegitration: typeof import('./src/components/UserRegitration.vue')['default']
    VehicalNavigation: typeof import('./src/components/VehicalNavigation.vue')['default']
    VehicleEdidt: typeof import('./src/components/VehicleEdidt.vue')['default']
    VehicleRegistration: typeof import('./src/components/VehicleRegistration.vue')['default']
    Vehicles: typeof import('./src/components/Vehicles.vue')['default']
  }
}
